#2.配置相关信息
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/ssm_db?serverTimezone=UTC
      username: root
      password: 123456
